Interactive list mileStone-2
alexander16108/to-do-list pull request #3
Opened 2021-07-21 20:17 UTC by alexander16108

2021-07-21 21:54 UTC, mricanho requested changes
Hi @alexander16108, 

Good job so far! You are using gitflow like a pro, and your JS code is clear and easy to follow 🔥🔥

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

![believe in change](https://user-images.githubusercontent.com/60631456/126565184-852043f9-4725-4d96-babf-9b30c128789d.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-21 21:54 UTC, mricanho commented on README.md
> +       -     https://webpack.js.org/guides/
- [ ] Add instructions, step by step about how to run your project, e.g. npm install, npm start, etc.

2021-07-21 21:54 UTC, mricanho commented on assets/src/dragdrop.js
> +}
- [ ] Something around here it's preventing that the tasks move in the list, please debug it and double-check that your app works before summit your project again, check the gif below.

![chrome-capture](https://user-images.githubusercontent.com/60631456/126565043-9d3fedeb-5f1a-44c5-98a1-f004b37afa18.gif)

2021-07-22 21:41 UTC, alexander16108 commented on assets/src/dragdrop.js
> +}
thank you for the feedback well so far I have  make some change to the code to fix that

2021-07-22 21:42 UTC, alexander16108 commented on README.md
> +       -     https://webpack.js.org/guides/
ok I have done thank you, I will pay more attention to details next time

2021-07-22 22:12 UTC, Dipeshtwis requested changes
Hi @alexander16108, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Required Changes ♻️
**_Check the comments under the review._**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

**_Check the comments under the review._**


Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**

-------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-22 22:12 UTC, Dipeshtwis commented on README.md
> +       -     https://webpack.js.org/guides/
- [ ] `npm start` is not working since you've not mentioned `start` in `package.json` file. 

Instead that I had followed this step 

```
npm install
npm run build and then open `index.html` in `dist` folder
```

You can mention these step or you can mention the `start` script in `package.json` file.

2021-07-22 22:12 UTC, Dipeshtwis commented on README.md
> +
[OPTIONAL]

- I would highly recommend to configure github pages correctly. Right now, I can see the readme in the live link.

2021-07-23 07:20 UTC, mikenath223 approved these changes
Hello there  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the PR thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-23 09:48 UTC, merged